# Generated by Django 4.1.3 on 2022-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0025_alter_staticcost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(default=None, max_length=200)),
                ('tax_sum', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
