# Generated by Django 4.1.3 on 2023-01-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salary", "0026_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staticcash",
            name="date",
        ),
        migrations.RemoveField(
            model_name="staticcost",
            name="date",
        ),
    ]
