# Generated by Django 4.1.3 on 2023-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary", "0027_remove_staticcash_date_remove_staticcost_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_inn",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
