# Generated by Django 4.1.3 on 2023-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary", "0028_client_client_inn_alter_client_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cash",
            name="operation_id",
            field=models.CharField(blank=True, default="", max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_inn",
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_department",
            field=models.CharField(
                choices=[
                    ("Менеджмент", "Менеджмент"),
                    ("Отдел продаж", "Отдел продаж"),
                    ("Отдел маркетинга", "Отдел маркетинга"),
                    (
                        "Отдел сопровождения клиентов (аккаунт)",
                        "Отдел по сопровождения клиентов (аккаунт)",
                    ),
                    ("IT отдел", "IT отдел"),
                ],
                max_length=40,
            ),
        ),
    ]
