# Generated by Django 4.1.3 on 2023-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary", "0029_cash_operation_id_alter_client_client_inn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_admission",
            field=models.DateField(default="2023-03-13"),
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Менеджер по продажам", "Менеджер по продажам"),
                    ("Аккаунт-менеджер (junior)", "Аккаунт-менеджер (junior)"),
                    ("Аккаунт-менеджер (middle)", "Аккаунт-менеджер (middle)"),
                    ("Аккаунт-менеджер (senior)", "Аккаунт-менеджер (senior)"),
                    ("Младший маркетолог", "Младший маркетолог"),
                    ("Интернет-маркетолог", "Интернет-маркетолог"),
                    ("Call-оператор", "Call-оператор"),
                    ("Верстальщик", "Верстальщик"),
                    ("Дизайнер", "Дизайнер"),
                    ("Специалист по PR", "Специалист по PR"),
                    ("Рекрутер", "Рекрутер"),
                    ("CRM-менеджер", "CRM-менеджер"),
                    ("РОА", "РОА"),
                    ("РОМ", "РОМ"),
                    (
                        "Ассистент директора, бухгалтер",
                        "Ассистент директора, бухгалтер",
                    ),
                ],
                default="Работает",
                max_length=40,
                null=True,
            ),
        ),
    ]
